# Generated by Django 3.1.7 on 2021-03-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210325_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['dia_semana', 'inicio']},
        ),
        migrations.AddField(
            model_name='turma',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
